CREATE TABLE _user (
userID SERIAL PRIMARY KEY,
userName VARCHAR(250) NOT NULL UNIQUE,
password VARCHAR(250) NOT NULL,
screenName VARCHAR(250) NOT NULL
);

CREATE TABLE _building (
buildingID SERIAL PRIMARY KEY,
path VARCHAR(250) NOT NULL UNIQUE,
name VARCHAR(100) NOT NULL
);

CREATE TABLE _post (
postID SERIAL PRIMARY KEY,
postedUserID SMALLINT NOT NULL,
FOREIGN KEY (postedUserID) REFERENCES _user(userID),
buildingID SMALLINT NOT NULL,
FOREIGN KEY (buildingID) REFERENCES _building(buildingID),
post VARCHAR(5000) NOT NULL,
time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
private BOOLEAN NOT NULL
);

CREATE TABLE _comment (
commentID SERIAL PRIMARY KEY,
postID SMALLINT NOT NULL,
FOREIGN KEY (postID) REFERENCES _post(postID),
comment VARCHAR(5000) NOT NULL,
commentUserID SMALLINT NOT NULL,
FOREIGN KEY (commentUserID) REFERENCES _user(userID)
);
